"""Compile explicitly validated, observable counter edges into portable C++ data."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
MAPS={'arena','Colosseum','default_small','default','schooltime','trophy'}
STYLES={'swarm':'SwarmObserved','long-body':'LongBodyObserved'}
PHASES={'early':'Early','middle':'Middle','late':'Late'}
FIELDS=('expand','workers','cautiousChild','target','splitLength','stop','reserve','reserveStop','continuation')


def export(graphs,profiles,maps_dir,output):
    rules=[]
    for graph in graphs:
        for edge in graph['edges']:
            if not edge.get('runtime_enabled'):continue
            name=graph['map'];phase=graph['phase'];style=edge.get('opponent_style')
            if name not in MAPS or phase not in PHASES or style not in STYLES:
                raise ValueError('Enabled edge lacks a supported observable map/style/phase')
            if hashlib.sha256((maps_dir/(name+'.map')).read_bytes()).hexdigest()!=graph['map_sha']:
                raise ValueError('Map revision changed')
            weight=edge.get('weight',edge.get('score'))
            if edge.get('relation')!='observed_advantage' or not isinstance(weight,(float,int)) or not math.isfinite(weight) or not .5<weight<=1:
                raise ValueError('Invalid counter weight')
            profile=profiles.get(edge['source'])
            if not profile or profile.get('map')!=name or not profile.get('validated'):
                raise ValueError('No validated executable policy for counter source')
            patch=profile['patch']
            if not patch or set(patch)-set(FIELDS): raise ValueError('Invalid policy fields')
            values=[]
            for field in FIELDS:
                value=patch.get(field,-1)
                if not isinstance(value,(int,float)) or not math.isfinite(value):raise ValueError('Invalid policy value')
                if field in patch:
                    if field in FIELDS[:3] and value not in (0,1):raise ValueError('Invalid boolean')
                    if field!='continuation' and (int(value)!=value or not 0<=value<=500):raise ValueError('Invalid integer')
                    if field=='continuation' and not 0<=value<=10:raise ValueError('Invalid continuation')
                values.append(str(value))
            rules.append('    adaptation::Rule{'+json.dumps(name)+','+json.dumps(edge['source'])+
                ',adaptation::Style::'+STYLES[style]+',adaptation::Phase::'+PHASES[phase]+','+str(weight)+
                ',adaptation::Patch{'+','.join(values)+'}}')
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text('// Generated by export_counter_rules.py; do not add unvalidated edges.\n#pragma once\n'
        '#include "strategy_adaptation.hpp"\nnamespace counter_rules {\n'
        f'inline constexpr std::array<adaptation::Rule,{len(rules)}> rules{{{{\n'+',\n'.join(rules)+'\n}};\n}\n',encoding='utf-8')
    return len(rules)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--graphs',type=Path,default=ROOT/'battlecode_data/strategy_library/map_graphs.json')
    parser.add_argument('--profiles',type=Path,default=ROOT/'battlecode_data/strategy_library/runtime_profiles.json')
    parser.add_argument('--output',type=Path,default=ROOT/'Leviathan1/counter_rules.hpp')
    args=parser.parse_args()
    profiles=json.loads(args.profiles.read_text()) if args.profiles.exists() else {}
    print('Exported validated rules:',export(json.loads(args.graphs.read_text()),profiles,ROOT/'maps',args.output))
